# defines the name of the github action
name: NASA Project Continuous Integration
on:
  push: # push requests, master branch will be affected
    branches: [master]
  pull_request: # pull requests, master branch will be affected
    branches: [master]
jobs:
  build:
    # run on ubuntu is preferred
    runs-on: ubuntu-latest
    # steps to run, each step is defined with a bullet point
    steps:
      - uses: actions/checkout@v2
      - name: Use node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - run: npm install
      - run: npm run build --prefix client
